version: '3.6'

services:

  db:
    image: mariadb
    restart: always   
    volumes:
      - ./db:/var/lib/mysql
    env_file: ./env/db
 
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  site:
    container_name: my-app
    build:
      context: .
      dockerfile: Dockerfile
    restart: always    
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./src:/var/www/html
